.\" dem-cli.1 --
.\" Copyright 2018-2019 Intel Corporation, Inc.
.\" May be distributed under the GNU General Public License
.TH DEM-CLI 1 "February 2019" "nvmeof-dem" "System Administration"
.SH NAME
dem-cli \-
Distributed Endpoint Management - Command-line interface
.SH SYNOPSIS
.B dem-cli
is the command-line interface used to manage and configure NVMe-oF networks
using Distributed Endpoint Management
.SH DESCRIPTION
.B dem-cli
is a program that interacts with a Distributed Endpoint Manager (DEM) to
manage the configuration of the NVMe-oF network.  The interface uses RESTful
commands to communicate with the Discovery
controller.

.SH PARAMETERS
.TP
.I -s <service>
network address of the DEM (defaulti: 127.0.0.1)
.TP
.I -p <port>
port of the DEM (see help for default)
.TP
.I -f
force deleted i.e. do not ask 'Are you sure'
.TP
.I -j
display the results in json format (default is to display in human-readable
format)
.TP
.I -r
display the results in raw (unmodified) format (used for debugging)
.TP
.I -c
show the curl commands (used for debugging)

.SH SEE ALSO
.BR dem (8),
.BR dem-ac (8),
.BR dem-em
.SH AVAILABILITY
The dem-cli command is part of the nvmeof-dem package and is available from
http://github.com/linux-nvme/dem.
