.\" dem-ec.8 --
.\" Copyright 2018 Intel Corporation, Inc.
.\" May be distributed under the GNU General Public License
.TH DEM-EC 8 "March 2018" "nvmeof-dem" "System Administration"
.SH NAME
dem-ec \-
Distributed Endpoint Management - Endpoint Configuration
.SH SYNOPSIS
.B dem-ec
is used on an Endpoint to allow a Discovery controller to configure NVMe-oF
resources to be exports on the NVMe-of network using Distributed Endpoint
Management
.SH DESCRIPTION
.B dem-ec
is a program that can run as a daemon or standalone to interact with a
Discovery controller to configure the Endpoint's Subsystems and Port IDs.
the Discovery controller may configure the Endpoint In-Band over the same
fabric used to Hosts use to connect to the Subsystems or Out-of-Band over
a secure TCP network using a RESTful interface.

This program doesnot provide log pages or access to the Subsystem it mananger.

.SH PARAMETERS
.TP
.I -d
enable debug prints in log files
.TP
.I -s
run as a standalone process (default is daemon)
.TP
.I -p <port>
port from RESTful interface (see help for default)
.TP
.I -r <root>
root for RESTful interface (see help for default)
.TP
.I -c <cert_file>
cert file for RESTful interface use with ssl

.SH SEE ALSO
.BR dem (1),
.BR dem-ac (8),
.BR dem-dc (8),
.SH AVAILABILITY
The dem-ec command is part of the nvmeof-dem package and is available from
git://gitlab.org/.
