.\" dem-ac.8 --
.\" Copyright 
.\" May be distributed under the GNU General Public License
.TH DEM-AC 8 "February 2019" "nvmeof-dem" "System Administration"
.SH NAME
dem-ac \-
Distributed Endpoint Management - Auto Connect
.SH SYNOPSIS
.B dem-ac
can be used on an NVMe-oF Host to use a Discovery controller to automatically
connect to Subsystems within a NVMe-oF network. The Discovery controller may
provided by the Distributed Endpoint Manager (DEM) or may be provided by a
single Endpoint.
.SH DESCRIPTION
.B dem-ac
is a program that can run as a daemon or standalone on a NVMe-oF Host that
will connect to a Discovery controller to retrieve the log pages of the
Subsystems to which that Host has access.  The program with then attept to
connect to each Subsystem to establish a persistent connection that Subsystem
to appear as a local NMVe device to the Host.

.SH PARAMETERS
.TP
.I -d
enable debug prints in log files
.TP
.I -S
run as a standalone process (default is daemon)
.TP
.I -q <hostnqn>
the Host NQN to use for connecting to be the Discovery controller
.TP
.B Discovery controller info:
.TP
.I -t <trtype>
transport type to use, i.e. rdma, tcp, fc (see help for default)
.TP
.I -f <adrfam>
address family, i.e. ipv4, ipv6, fc (see help for default)
.TP
.I -a <traddr>
transport address to use, must match address family definition of an address
(see help for default)
.TP
.I -s <trsvcid>
transport service id (a.k.a. Port Number) to use. (see help for default)

.SH SEE ALSO
.BR dem-cli (1),
.BR dem (8),
.BR dem-em (8),
.SH AVAILABILITY
The dem-ac command is part of the nvmeof-dem package and is available from
http://github.com/linux-nvme/dem.
