.\" dem-em.8 --
.\" Copyright 2018-2019 Intel Corporation, Inc.
.\" May be distributed under the GNU General Public License
.TH DEM-EM 8 "February 2019" "nvmeof-dem" "System Administration"
.SH NAME
dem-em \-
Distributed Endpoint Management - Endpoint Manager
.SH SYNOPSIS
.B dem-em
is used on an Endpoint to allow remote  configure NVMe-oF
resources to be exports on the NVMe-of network using Distributed Endpoint
Management
.SH DESCRIPTION
.B dem-em
is a program that can run as a daemon or standalone to interact with a
Distributed Endpoint Manager (DEM) to configure the Endpoint's Subsystems and
Port IDs.  DEM may configure the Endpoint In-Band over the same
fabric used to Hosts use to connect to the Subsystems or Out-of-Band over
a secure TCP network using a RESTful interface.

This program doesnot provide log pages or access to the Subsystem it mananger.

.SH PARAMETERS
.TP
.I -d
enable debug prints in log files
.TP
.I -S
run as a standalone process (default is daemon)
.TP
.B Out-of-Band Management Mode
.TP
.I -p <port>
port from RESTful interface (see help for default)
.TP
.I -r <root>
root for RESTful interface (see help for default)
.TP
.I -c <cert_file>
cert file for RESTful interface use with ssl (default is to not use ssl)
.TP
.B In-Band Management Mode
.TP
.I -t <trtype>
transport type to use, i.e. rdma, tcp, fc (see help for default)
.TP
.I -f <adrfam>
address family, i.e. ipv4, ipv6, fc (see help for default)
.TP
.I -a <traddr>
transport address to use, must match address family definition of an address
(see help for default)
.TP
.I -s <trsvcid>
transport service id (a.k.a. Port Number) to use. (see help for default)

.SH SEE ALSO
.BR dem-cli (1),
.BR dem-ac (8),
.BR dem (8),
.SH AVAILABILITY
The dem-em command is part of the nvmeof-dem package and is available from
http://github.com/linux-nvme/dem.
